// create and export object with logo image as urls from web
export const valorantLogos = {
  Valorant: "https://cdn3.emoji.gg/emojis/9309_valorant_logo.png",
  "Iron 1": "https://cdn3.emoji.gg/emojis/3624-valorant-iron-1.png",
  "Iron 2": "https://cdn3.emoji.gg/emojis/7351-valorant-iron-2.png",
  "Iron 3": "https://cdn3.emoji.gg/emojis/1854-valorant-iron-3.png",
  "Bronze 1": "https://cdn3.emoji.gg/emojis/4159-valorant-bronze-1.png",
  "Bronze 2": "https://cdn3.emoji.gg/emojis/4376-valorant-bronze-2.png",
  "Bronze 3": "https://cdn3.emoji.gg/emojis/4590-valorant-bronze-3.png",
  "Silver 1": "https://cdn3.emoji.gg/emojis/6335-valorant-silver-1.png",
  "Silver 2": "https://cdn3.emoji.gg/emojis/8138-valorant-silver-2.png",
  "Silver 3": "https://cdn3.emoji.gg/emojis/3293-valorant-silver-3.png",
  "Gold 1": "https://cdn3.emoji.gg/emojis/5533-valorant-gold-1.png",
  "Gold 2": "https://cdn3.emoji.gg/emojis/2060-valorant-gold-2.png",
  "Gold 3": "https://cdn3.emoji.gg/emojis/3293-valorant-gold-3.png",
  "Platinum 1": "https://cdn3.emoji.gg/emojis/4590-valorant-platinum-1.png",
  "Platinum 2": "https://cdn3.emoji.gg/emojis/3255-valorant-platinum-2.png",
  "Platinum 3": "https://cdn3.emoji.gg/emojis/5816-valorant-platinum-3.png",
  "Diamond 1": "https://cdn3.emoji.gg/emojis/4590-valorant-diamond-1.png",
  "Diamond 2": "https://cdn3.emoji.gg/emojis/3939-valorant-diamond-2.png",
  "Diamond 3": "https://cdn3.emoji.gg/emojis/6354-valorant-diamond-3.png",
  "Ascendant 1": "https://cdn3.emoji.gg/emojis/4590-valorant-ascendant-1.png",
  "Ascendant 2": "https://cdn3.emoji.gg/emojis/8376-valorant-ascendant-2.png",
  "Ascendant 3": "https://cdn3.emoji.gg/emojis/2309-valorant-ascendant-3.png",
  "Immortal 1": "https://cdn3.emoji.gg/emojis/1518-valorant-immortal-1.png",
  "Immortal 2": "https://cdn3.emoji.gg/emojis/1775-valorant-immortal-2.png",
  "Immortal 3": "https://cdn3.emoji.gg/emojis/5979-valorant-immortal-3.png",
  Radiant: "https://cdn3.emoji.gg/emojis/5979-valorant-radiant.png",
};
